config/routes.rb
Rails.application.routes.draw do
  
  resources :recados
  root 'recados#new'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recado.rb
class Recado < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recados_controller.rb
class RecadosController < ApplicationController
  before_action :set_recado, only: %i[ show edit update destroy ]

  # GET /recados or /recados.json
  def index
    @recados = Recado.all
  end

  # GET /recados/1 or /recados/1.json
  def show
  end

  # GET /recados/new
  def new
    
    @recados = Recado.all

    @recado = Recado.new
  end

  # GET /recados/1/edit
  def edit
  end

  # POST /recados or /recados.json
  def create
    @recado = Recado.new(recado_params)

    respond_to do |format|
      if @recado.save
        format.html { redirect_to root_url}
        format.json { render :show, status: :created, location: @recado }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recados/1 or /recados/1.json
  def update
    respond_to do |format|
      if @recado.update(recado_params)
        format.html { redirect_to recados_url, notice: "Anotação editada." }
        format.json { render :show, status: :ok, location: @recado }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recados/1 or /recados/1.json
  def destroy
    @recado.destroy

    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recado
      @recado = Recado.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recado_params
      params.require(:recado).permit(:descricao, :autor)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recados_helper.rb
module RecadosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nosso quadro</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>    
  </body>
</html>

app/views/recados/_form.html.erb
<%= form_with(model: recado, local: true) do |form| %>
  <% if recado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recado.errors.count, "error") %> prohibited this recado from being saved:</h2>

      <ul>
      <% recado.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
     
  <!-- div class="radio-group">
    <%= form.label :autor, "Autor:" %>
    <br> 
    <%= form.radio_button :autor, 'Cesar'  %> Cesar   
    <br>
    <%= form.radio_button :autor, 'Charles' %> Charles
    <br>
    <%= form.radio_button :autor, 'Edson'  %> Edson
    <br>
    <%= form.radio_button :autor, 'Fabi'   %>  Fabi
    <br>
    <%= form.radio_button :autor, 'Gera'   %> Gera
    <br>
    <%= form.radio_button :autor, 'Sidnei' %> Sidnei
  </div -->
  
  <br>

  <div class="form-group">
    <%= form.label :descricao, "Anotação :" %>
    <%= form.text_area :descricao, class: "form-control", cols: 15, rows: 1 %>
  </div>


  <div class="actions">
    <%= form.submit "Adicionar", class: 'btn btn-outline-primary'  %>
  </div>
<% end %>

app/views/recados/edit.html.erb
<br>
<h2>Editar Recado</h2>
<br>
<%= render 'form', recado: @recado %>

app/views/recados/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recados</h1>

<%= link_to 'Escrever', new_recado_path, class: 'btn btn-outline-primary'  %>
<br>
<br>

  <table>
    <thead>
      <tr>
        <th></th>
      </tr>
    </thead>

    <tbody>
        <%# <tr> %>
          <% @recados.each do |recado| %>
              <%# <td> %>
                <tr>
                  <td>
                    <div class="card bg-warning mb-3" style="max-width: 14rem;">
                      <div class="card-body">
                        <p class="card-text">
                          <small class="text-muted"><b><cite title="Source Title"><%= recado.autor %></cite></b></small>
                        </p>
                        <p class="card-text"><b><%= recado.descricao %></b></p>
                        <%= link_to '...', edit_recado_path(recado), class: 'btn btn-outline-info' %>
                        <%= link_to 'X', recado, method: :delete, class: 'btn btn-outline-danger' %>
                    </div>
                  <td>
                </tr>
              <%# </td> %>
          <% end %>
        <%# </tr> %>
    </tbody>
  </table>

  <br>

app/views/recados/new.html.erb
<br>
<h2>Recado</h2>

<%= render 'form', recado: @recado %>

<br>


  <!-- table >
    <tbody>
    <% novalinha = true %>
          <% @recados.each do |recado| %>
                <% if novalinha == true  %>
                  <tr>
                    <td>
                      <div class="card bg-warning mb-3" style="max-width: 26rem;">
                        <div class="card-body">
                          <h3><b><%= recado.descricao %></b></h3>
                          <%= link_to 'X', recado, method: :delete, class: 'btn btn-outline-danger' %>
                      </div>
                    <td>

                  <% novalinha = false  %>
                <% else %>
                    <td>
                      <div class="card bg-warning mb-3" style="max-width: 26rem;">
                        <div class="card-body">
                          <h3><b><%= recado.descricao %></b></h3>
                          <%= link_to 'X', recado, method: :delete, class: 'btn btn-outline-danger' %>
                      </div>
                    <td>    
                    <% novalinha = true  %>    
                </tr>        
                <% end %>

          <% end %>
    </tbody>
  </table -->

<div class="cont">
  <% @recados.each do |recado| %>
    <div class="col">
      <div class="card bg-warning mb-3" >
        <div class="card-body">
          <h3><b><%= recado.descricao %></b></h3>
          <%= link_to 'X', recado, method: :delete, class: 'btn btn-outline-danger' %>
        </div>
      </div>
    </div>
  <% end %>
</div>


<br>

app/views/recados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descricao:</strong>
  <%= @recado.descricao %>
</p>

<p>
  <strong>Autor:</strong>
  <%= @recado.autor %>
</p>

<%= link_to 'Edit', edit_recado_path(@recado) %> |
<%= link_to 'Back', recados_path %>